{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/audiokit\/applesequencer\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/audiokit\/applesequencer\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AudioKit\/documentation\/AudioKit\/AppleSequencer\/init()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sequencer Initialization"}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@AudioKit@objc(cs)AppleSequencer(im)init","modules":[{"name":"AudioKit"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/AudioKit\/documentation\/AudioKit","doc:\/\/AudioKit\/documentation\/AudioKit\/AppleSequencer"]]},"references":{"doc://AudioKit/documentation/AudioKit/AppleSequencer":{"role":"symbol","title":"AppleSequencer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleSequencer"}],"abstract":[{"type":"text","text":"Sequencer based on tried-and-true CoreAudio\/MIDI Sequencing"}],"identifier":"doc:\/\/AudioKit\/documentation\/AudioKit\/AppleSequencer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppleSequencer"}],"url":"\/documentation\/audiokit\/applesequencer"},"doc://AudioKit/documentation/AudioKit":{"role":"collection","title":"AudioKit","abstract":[],"identifier":"doc:\/\/AudioKit\/documentation\/AudioKit","kind":"symbol","type":"topic","url":"\/documentation\/audiokit"},"doc://AudioKit/documentation/AudioKit/AppleSequencer/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Sequencer Initialization"}],"identifier":"doc:\/\/AudioKit\/documentation\/AudioKit\/AppleSequencer\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/audiokit\/applesequencer\/init()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["macOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AudioKit~1documentation~1AudioKit~1AppleSequencer\/title","value":"AppleSequencer"},{"op":"replace","path":"\/references\/doc:~1~1AudioKit~1documentation~1AudioKit~1AppleSequencer\/fragments","value":[{"kind":"identifier","text":"AppleSequencer"}]},{"op":"replace","path":"\/references\/doc:~1~1AudioKit~1documentation~1AudioKit~1AppleSequencer~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1AudioKit~1documentation~1AudioKit~1AppleSequencer~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}