{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MIDISystemRealTimeListener"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/audiokit\/midisystemrealtimelistener"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/audiokit\/midisystemrealtimelistener"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AudioKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AudioKit\/documentation\/AudioKit\/MIDIListener","doc:\/\/AudioKit\/objc(pl)NSObject","doc:\/\/AudioKit\/s7CVarArgP","doc:\/\/AudioKit\/s28CustomDebugStringConvertibleP","doc:\/\/AudioKit\/s23CustomStringConvertibleP","doc:\/\/AudioKit\/SQ","doc:\/\/AudioKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AudioKit\/documentation\/AudioKit\/MIDISystemRealTimeListener","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This MIDIListener looks for midi system real time (SRT)"},{"type":"text","text":" "},{"type":"text","text":"midi system messages."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MIDISystemRealTimeListener"}],"title":"MIDISystemRealTimeListener","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@AudioKit@objc(cs)MIDISystemRealTimeListener","modules":[{"name":"AudioKit"}],"navigatorTitle":[{"kind":"identifier","text":"MIDISystemRealTimeListener"}]},"hierarchy":{"paths":[["doc:\/\/AudioKit\/documentation\/AudioKit"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/AudioKit\/documentation\/AudioKit\/MIDISystemRealTimeListener\/addObserver(_:)","doc:\/\/AudioKit\/documentation\/AudioKit\/MIDISystemRealTimeListener\/removeAllObservers()","doc:\/\/AudioKit\/documentation\/AudioKit\/MIDISystemRealTimeListener\/removeObserver(_:)"]},{"title":"Enumerations","identifiers":["doc:\/\/AudioKit\/documentation\/AudioKit\/MIDISystemRealTimeListener\/SRTState"]},{"title":"Default Implementations","identifiers":["doc:\/\/AudioKit\/documentation\/AudioKit\/MIDISystemRealTimeListener\/MIDIListener-Implementations"],"generated":true}],"references":{"doc://AudioKit/documentation/AudioKit/MIDISystemRealTimeListener/removeObserver(_:)":{"role":"symbol","title":"removeObserver(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeObserver"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MIDISystemRealTimeObserver","preciseIdentifier":"s:8AudioKit26MIDISystemRealTimeObserverP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Remove MIDI System real-time observer"}],"identifier":"doc:\/\/AudioKit\/documentation\/AudioKit\/MIDISystemRealTimeListener\/removeObserver(_:)","kind":"symbol","type":"topic","url":"\/documentation\/audiokit\/midisystemrealtimelistener\/removeobserver(_:)"},"doc://AudioKit/documentation/AudioKit/MIDISystemRealTimeListener/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/AudioKit\/documentation\/AudioKit\/MIDISystemRealTimeListener\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/audiokit\/midisystemrealtimelistener\/init"},"doc://AudioKit/documentation/AudioKit/MIDISystemRealTimeListener/MIDIListener-Implementations":{"role":"collectionGroup","title":"MIDIListener Implementations","abstract":[],"identifier":"doc:\/\/AudioKit\/documentation\/AudioKit\/MIDISystemRealTimeListener\/MIDIListener-Implementations","kind":"article","type":"topic","url":"\/documentation\/audiokit\/midisystemrealtimelistener\/midilistener-implementations"},"doc://AudioKit/documentation/AudioKit/MIDIListener":{"role":"symbol","title":"MIDIListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MIDIListener"}],"abstract":[{"type":"text","text":"MIDI Listener protocol"}],"identifier":"doc:\/\/AudioKit\/documentation\/AudioKit\/MIDIListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MIDIListener"}],"url":"\/documentation\/audiokit\/midilistener"},"doc://AudioKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AudioKit\/SQ"},"doc://AudioKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AudioKit\/s23CustomStringConvertibleP"},"doc://AudioKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AudioKit\/objc(cs)NSObject"},"doc://AudioKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AudioKit\/s28CustomDebugStringConvertibleP"},"doc://AudioKit/documentation/AudioKit":{"role":"collection","title":"AudioKit","abstract":[],"identifier":"doc:\/\/AudioKit\/documentation\/AudioKit","kind":"symbol","type":"topic","url":"\/documentation\/audiokit"},"doc://AudioKit/documentation/AudioKit/MIDISystemRealTimeListener/removeAllObservers()":{"role":"symbol","title":"removeAllObservers()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAllObservers"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Remove all observers"}],"identifier":"doc:\/\/AudioKit\/documentation\/AudioKit\/MIDISystemRealTimeListener\/removeAllObservers()","kind":"symbol","type":"topic","url":"\/documentation\/audiokit\/midisystemrealtimelistener\/removeallobservers()"},"doc://AudioKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AudioKit\/SH"},"doc://AudioKit/documentation/AudioKit/MIDISystemRealTimeListener/SRTState":{"role":"symbol","title":"MIDISystemRealTimeListener.SRTState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SRTState"}],"abstract":[{"type":"text","text":"System real-time state"}],"identifier":"doc:\/\/AudioKit\/documentation\/AudioKit\/MIDISystemRealTimeListener\/SRTState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SRTState"}],"url":"\/documentation\/audiokit\/midisystemrealtimelistener\/srtstate"},"doc://AudioKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AudioKit\/s7CVarArgP"},"doc://AudioKit/documentation/AudioKit/MIDISystemRealTimeListener":{"role":"symbol","title":"MIDISystemRealTimeListener","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MIDISystemRealTimeListener"}],"abstract":[{"type":"text","text":"This MIDIListener looks for midi system real time (SRT)"},{"type":"text","text":" "},{"type":"text","text":"midi system messages."}],"identifier":"doc:\/\/AudioKit\/documentation\/AudioKit\/MIDISystemRealTimeListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MIDISystemRealTimeListener"}],"url":"\/documentation\/audiokit\/midisystemrealtimelistener"},"doc://AudioKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AudioKit\/objc(pl)NSObject"},"doc://AudioKit/documentation/AudioKit/MIDISystemRealTimeListener/addObserver(_:)":{"role":"symbol","title":"addObserver(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addObserver"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MIDISystemRealTimeObserver","preciseIdentifier":"s:8AudioKit26MIDISystemRealTimeObserverP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Add MIDI System real-time observer"}],"identifier":"doc:\/\/AudioKit\/documentation\/AudioKit\/MIDISystemRealTimeListener\/addObserver(_:)","kind":"symbol","type":"topic","url":"\/documentation\/audiokit\/midisystemrealtimelistener\/addobserver(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MIDISystemRealTimeListener"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MIDISystemRealTimeListener"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MIDISystemRealTimeListener"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/AudioKit\/documentation\/AudioKit\/MIDISystemRealTimeListener\/init"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MIDISystemRealTimeListener"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["macOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AudioKit~1documentation~1AudioKit~1MIDISystemRealTimeListener\/title","value":"MIDISystemRealTimeListener"},{"op":"replace","path":"\/references\/doc:~1~1AudioKit~1documentation~1AudioKit~1MIDISystemRealTimeListener\/fragments","value":[{"kind":"identifier","text":"MIDISystemRealTimeListener"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}