{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MIDIOMNIListener"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/audiokit\/midiomnilistener"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/audiokit\/midiomnilistener"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AudioKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AudioKit\/documentation\/AudioKit\/MIDIListener","doc:\/\/AudioKit\/objc(pl)NSObject","doc:\/\/AudioKit\/s7CVarArgP","doc:\/\/AudioKit\/s28CustomDebugStringConvertibleP","doc:\/\/AudioKit\/s23CustomStringConvertibleP","doc:\/\/AudioKit\/SQ","doc:\/\/AudioKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AudioKit\/documentation\/AudioKit\/MIDIOMNIListener","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This class probably needs to support observers as well"},{"type":"text","text":" "},{"type":"text","text":"so that a client may be able to be notified of state changes"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MIDIOMNIListener"}],"title":"MIDIOMNIListener","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@AudioKit@objc(cs)MIDIOMNIListener","modules":[{"name":"AudioKit"}],"navigatorTitle":[{"kind":"identifier","text":"MIDIOMNIListener"}]},"hierarchy":{"paths":[["doc:\/\/AudioKit\/documentation\/AudioKit"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/AudioKit\/documentation\/AudioKit\/MIDIOMNIListener\/init(omni:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/AudioKit\/documentation\/AudioKit\/MIDIOMNIListener\/omniStateChange()"]},{"title":"Default Implementations","identifiers":["doc:\/\/AudioKit\/documentation\/AudioKit\/MIDIOMNIListener\/MIDIListener-Implementations"],"generated":true}],"references":{"doc://AudioKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AudioKit\/SQ"},"doc://AudioKit/documentation/AudioKit/MIDIOMNIListener/omniStateChange()":{"role":"symbol","title":"omniStateChange()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"omniStateChange"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"OMNI State Change - override in subclass"}],"identifier":"doc:\/\/AudioKit\/documentation\/AudioKit\/MIDIOMNIListener\/omniStateChange()","kind":"symbol","type":"topic","url":"\/documentation\/audiokit\/midiomnilistener\/omnistatechange()"},"doc://AudioKit/documentation/AudioKit/MIDIOMNIListener/MIDIListener-Implementations":{"role":"collectionGroup","title":"MIDIListener Implementations","abstract":[],"identifier":"doc:\/\/AudioKit\/documentation\/AudioKit\/MIDIOMNIListener\/MIDIListener-Implementations","kind":"article","type":"topic","url":"\/documentation\/audiokit\/midiomnilistener\/midilistener-implementations"},"doc://AudioKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AudioKit\/s28CustomDebugStringConvertibleP"},"doc://AudioKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AudioKit\/objc(pl)NSObject"},"doc://AudioKit/documentation/AudioKit/MIDIListener":{"role":"symbol","title":"MIDIListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MIDIListener"}],"abstract":[{"type":"text","text":"MIDI Listener protocol"}],"identifier":"doc:\/\/AudioKit\/documentation\/AudioKit\/MIDIListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MIDIListener"}],"url":"\/documentation\/audiokit\/midilistener"},"doc://AudioKit/documentation/AudioKit":{"role":"collection","title":"AudioKit","abstract":[],"identifier":"doc:\/\/AudioKit\/documentation\/AudioKit","kind":"symbol","type":"topic","url":"\/documentation\/audiokit"},"doc://AudioKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AudioKit\/s7CVarArgP"},"doc://AudioKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AudioKit\/s23CustomStringConvertibleP"},"doc://AudioKit/documentation/AudioKit/MIDIOMNIListener/init(omni:)":{"role":"symbol","title":"init(omni:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"omni"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize with omni mode"}],"identifier":"doc:\/\/AudioKit\/documentation\/AudioKit\/MIDIOMNIListener\/init(omni:)","kind":"symbol","type":"topic","url":"\/documentation\/audiokit\/midiomnilistener\/init(omni:)"},"doc://AudioKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AudioKit\/objc(cs)NSObject"},"doc://AudioKit/documentation/AudioKit/MIDIOMNIListener":{"role":"symbol","title":"MIDIOMNIListener","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MIDIOMNIListener"}],"abstract":[{"type":"text","text":"This class probably needs to support observers as well"},{"type":"text","text":" "},{"type":"text","text":"so that a client may be able to be notified of state changes"}],"identifier":"doc:\/\/AudioKit\/documentation\/AudioKit\/MIDIOMNIListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MIDIOMNIListener"}],"url":"\/documentation\/audiokit\/midiomnilistener"},"doc://AudioKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AudioKit\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MIDIOMNIListener"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MIDIOMNIListener"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MIDIOMNIListener"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MIDIOMNIListener"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["macOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AudioKit~1documentation~1AudioKit~1MIDIOMNIListener\/title","value":"MIDIOMNIListener"},{"op":"replace","path":"\/references\/doc:~1~1AudioKit~1documentation~1AudioKit~1MIDIOMNIListener\/fragments","value":[{"kind":"identifier","text":"MIDIOMNIListener"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}